# Frontend/Dockerfile
FROM node:alpine

WORKDIR /app/e-commerce-frontend

COPY package.json ./
COPY package-lock.json ./

RUN npm install
RUN npm install react-router-dom
RUN npm install axios
RUN npm install jest-fetch-mock --save-dev
RUN npm install node-fetch --save-dev



COPY . .

EXPOSE 3000

CMD ["npm", "run", "start"]

